# Generated by Django 3.2.16 on 2022-11-01 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_image_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='order_numb',
            field=models.SmallIntegerField(default=None, verbose_name='Порядок'),
            preserve_default=False,
        ),
    ]
